# Generated by Django 4.1.6 on 2023-05-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_is_active_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecificationvalue',
            options={'verbose_name': 'Product Specification Value', 'verbose_name_plural': 'Products Specification Values'},
        ),
    ]
