# Generated by Django 4.1.6 on 2023-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productspecificationvalue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_ar',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_es',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_fr',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ja',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tr',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_uz',
            field=models.CharField(default='white', max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ja',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default='Description coming soon', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fr',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ja',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Product title'),
        ),
    ]
